// Mô tả các bảng Supabase cho trang "Dữ liệu" của admin (xem supabase/migrations/).
// Mỗi cột: { key, label, type, required?, options?, ref?, list?, readOnly?, hint? }
//   type: text | textarea | number | int | date | time | enum | multi | tags | json | ref | bool | datetime
//   ref:  bảng được liên kết → hiển thị bằng tên thay vì mã, chọn bằng ô tìm kiếm
//   list: hiện trong bảng danh sách (mặc định ẩn)
// Quyền: canInsert / canUpdate / canDelete = false khi RLS không cho admin, hoặc dữ liệu chỉ ghi qua hàm.
import { DOW_FULL, LEVELS, SPORTS, SPORT_ORDER } from "@/lib/clubs/model";

const SEX = [
  { value: "male", label: "Nam" },
  { value: "female", label: "Nữ" },
];
const SEMESTER = [
  { value: "Học kỳ I", label: "Học kỳ I" },
  { value: "Học kỳ II", label: "Học kỳ II" },
];
const ROLES = [
  { value: "admin", label: "Quản trị" },
  { value: "lead", label: "Tổ trưởng Tổ Thể dục" },
  { value: "hr", label: "Phòng Nhân sự" },
  { value: "teacher", label: "Giáo viên" },
  { value: "user", label: "Tài khoản thường" },
];
const EVIDENCE_STATUS = [
  { value: "pending", label: "Chờ duyệt" },
  { value: "approved", label: "Đã duyệt" },
  { value: "rejected", label: "Bị từ chối" },
];
const NUTRITION = ["Bình thường", "Thừa cân", "Béo phì", "Gầy còm", "Gầy còm nặng"].map((v) => ({ value: v, label: v }));

const created = { key: "created_date", label: "Ngày tạo", type: "datetime", readOnly: true };

// Bảng được liên kết: cột hiển thị + cột tìm kiếm
export const REFS = {
  students: { label: (r) => `${r.full_name}${r.grade ? ` · K${r.grade}` : ""}${r.school_year ? ` · ${r.school_year}` : ""}`, select: "id, full_name, grade, school_year", search: "full_name" },
  classes: { label: (r) => `${r.name} · ${r.school_year}${r.campus ? ` · ${r.campus}` : ""}`, select: "id, name, school_year, campus", search: "name" },
  test_sessions: { label: (r) => `${r.name} · ${r.school_year}`, select: "id, name, school_year", search: "name" },
  teachers: { label: (r) => r.full_name, select: "id, full_name", search: "full_name" },
  clubs: { label: (r) => r.name, select: "id, name", search: "name" },
  profiles: { label: (r) => r.full_name || r.email, select: "id, full_name, email", search: "full_name,email" },
  evidence_sessions: { label: (r) => r.session_date, select: "id, session_date", search: null },
};

export const GROUPS = [
  { key: "fitness", label: "Thể lực" },
  { key: "clubs", label: "Câu lạc bộ" },
  { key: "accounts", label: "Tài khoản" },
  { key: "system", label: "Hệ thống" },
];

export const TABLES = [
  /* ------------------------------ Thể lực ------------------------------ */
  {
    key: "students",
    group: "fitness",
    label: "Học sinh",
    search: ["full_name", "student_code"],
    sort: "full_name",
    columns: [
      { key: "full_name", label: "Họ tên", type: "text", required: true, list: true },
      { key: "student_code", label: "Mã học sinh", type: "text", list: true },
      { key: "sex", label: "Giới tính", type: "enum", options: SEX, required: true, list: true },
      { key: "birth_date", label: "Ngày sinh", type: "date", required: true, list: true },
      { key: "class_id", label: "Lớp", type: "ref", ref: "classes", required: true, list: true },
      { key: "grade", label: "Khối", type: "text", required: true, list: true, hint: "Số khối, vd 1, 6, 12" },
      { key: "campus", label: "Cơ sở", type: "text", list: true },
      { key: "school_year", label: "Năm học", type: "text", required: true, list: true, hint: "vd 2026-2027" },
      { key: "avatar_url", label: "Ảnh đại diện (URL)", type: "text" },
      created,
    ],
    deleteNote: "Xoá học sinh sẽ xoá luôn kết quả thể lực, thể trạng và nhận xét của em đó.",
    cascade: ["fitness_results", "anthropometric_results", "teacher_comments"],
  },
  {
    key: "classes",
    group: "fitness",
    label: "Lớp học",
    search: ["name", "campus"],
    sort: "name",
    columns: [
      { key: "name", label: "Tên lớp", type: "text", required: true, list: true },
      { key: "grade", label: "Khối", type: "text", required: true, list: true },
      { key: "campus", label: "Cơ sở", type: "text", list: true },
      { key: "school_year", label: "Năm học", type: "text", required: true, list: true },
      { key: "teacher_id", label: "Giáo viên chủ nhiệm", type: "ref", ref: "teachers", list: true },
      created,
    ],
  },
  {
    key: "test_sessions",
    group: "fitness",
    label: "Đợt kiểm tra",
    search: ["name", "school_year"],
    sort: "-test_date",
    columns: [
      { key: "name", label: "Tên đợt", type: "text", required: true, list: true },
      { key: "test_date", label: "Ngày kiểm tra", type: "date", required: true, list: true },
      { key: "semester", label: "Học kỳ", type: "enum", options: SEMESTER, required: true, list: true },
      { key: "school_year", label: "Năm học", type: "text", required: true, list: true },
      { key: "teacher_id", label: "Giáo viên phụ trách", type: "ref", ref: "teachers" },
      { key: "notes", label: "Ghi chú", type: "textarea", list: true },
      created,
    ],
  },
  {
    key: "fitness_results",
    group: "fitness",
    label: "Kết quả thể lực",
    sort: "-created_date",
    filters: ["session_id", "student_id"],
    columns: [
      { key: "student_id", label: "Học sinh", type: "ref", ref: "students", required: true, list: true },
      { key: "session_id", label: "Đợt kiểm tra", type: "ref", ref: "test_sessions", required: true, list: true },
      { key: "pacer_laps", label: "PACER (tổng lượt)", type: "number", list: true },
      { key: "pacer_level", label: "PACER (level)", type: "number" },
      { key: "pacer_type", label: "Đường chạy PACER", type: "enum", options: [{ value: "15m", label: "15m" }, { value: "20m", label: "20m" }], list: true },
      { key: "sit_and_reach_cm", label: "Sit-and-Reach (cm)", type: "number", list: true },
      { key: "pushup_count", label: "Push-up (lần)", type: "number", list: true },
      { key: "plank_seconds", label: "Plank (giây)", type: "number", list: true },
      { key: "long_jump_cm", label: "Bộ GD: Bật xa tại chỗ (cm)", type: "number", list: true },
      { key: "run_5min_m", label: "Bộ GD: Chạy tuỳ sức 5 phút (m)", type: "number", list: true },
      { key: "situps_30s", label: "Bộ GD: Gập bụng (lần/30 giây)", type: "number", list: true },
      { key: "sprint_30m_s", label: "Bộ GD: Chạy 30m (giây)", type: "number", list: true },
      { key: "grip_strength_kg", label: "Bộ GD: Lực bóp tay (kg)", type: "number" },
      { key: "shuttle_4x10_s", label: "Bộ GD: Con thoi 4×10m (giây)", type: "number" },
      { key: "teacher_id", label: "Giáo viên đo", type: "ref", ref: "teachers" },
      created,
    ],
  },
  {
    key: "anthropometric_results",
    group: "fitness",
    label: "Chiều cao – cân nặng",
    sort: "-created_date",
    filters: ["session_id", "student_id"],
    columns: [
      { key: "student_id", label: "Học sinh", type: "ref", ref: "students", required: true, list: true },
      { key: "session_id", label: "Đợt kiểm tra", type: "ref", ref: "test_sessions", required: true, list: true },
      { key: "height_cm", label: "Chiều cao (cm)", type: "number", required: true, list: true },
      { key: "weight_kg", label: "Cân nặng (kg)", type: "number", required: true, list: true },
      { key: "bmi", label: "BMI", type: "number", list: true, hint: "Để trống thì app tự tính khi hiển thị" },
      { key: "age_months", label: "Tuổi (tháng)", type: "number" },
      { key: "bmi_for_age_zscore", label: "Z-score BMI", type: "number" },
      { key: "nutritional_status", label: "Tình trạng dinh dưỡng", type: "enum", options: NUTRITION, list: true },
      created,
    ],
  },
  {
    key: "teacher_comments",
    group: "fitness",
    label: "Nhận xét giáo viên",
    sort: "-created_date",
    filters: ["session_id", "student_id"],
    search: ["fitness_comment", "growth_comment", "recommendation"],
    columns: [
      { key: "student_id", label: "Học sinh", type: "ref", ref: "students", required: true, list: true },
      { key: "session_id", label: "Đợt kiểm tra", type: "ref", ref: "test_sessions", required: true, list: true },
      { key: "teacher_id", label: "Giáo viên", type: "ref", ref: "teachers" },
      { key: "fitness_comment", label: "Nhận xét thể lực", type: "textarea", list: true },
      { key: "growth_comment", label: "Nhận xét phát triển", type: "textarea" },
      { key: "recommendation", label: "Khuyến nghị", type: "textarea" },
      created,
    ],
  },
  {
    key: "teachers",
    group: "fitness",
    label: "Giáo viên",
    search: ["full_name", "email", "phone"],
    sort: "full_name",
    columns: [
      { key: "full_name", label: "Họ tên", type: "text", required: true, list: true },
      { key: "email", label: "Email", type: "text", required: true, list: true },
      { key: "phone", label: "Điện thoại", type: "text", list: true },
      { key: "campus", label: "Cơ sở", type: "text", list: true },
      { key: "assigned_classes", label: "Lớp phụ trách (mã)", type: "tags" },
      created,
    ],
  },
  {
    key: "parents",
    group: "fitness",
    label: "Phụ huynh",
    search: ["full_name", "email", "phone"],
    sort: "full_name",
    columns: [
      { key: "full_name", label: "Họ tên", type: "text", required: true, list: true },
      { key: "email", label: "Email", type: "text", required: true, list: true },
      { key: "phone", label: "Điện thoại", type: "text", list: true },
      { key: "student_ids", label: "Mã học sinh liên kết", type: "tags" },
      created,
    ],
  },
  {
    key: "parent_student_relationships",
    group: "fitness",
    label: "Liên kết phụ huynh – học sinh",
    search: ["parent_email", "relationship"],
    sort: "-created_date",
    columns: [
      { key: "parent_email", label: "Email phụ huynh", type: "text", required: true, list: true },
      { key: "student_id", label: "Học sinh", type: "ref", ref: "students", required: true, list: true },
      { key: "relationship", label: "Quan hệ", type: "text", list: true, hint: "vd Bố, Mẹ" },
      created,
    ],
  },
  {
    key: "who_bmi_references",
    group: "fitness",
    label: "Bảng chuẩn BMI WHO",
    sort: "age_months",
    canInsert: false,
    canUpdate: false,
    canDelete: false,
    note: "Bảng tham chiếu cố định của WHO — chỉ xem.",
    columns: [
      { key: "sex", label: "Giới tính", type: "enum", options: SEX, list: true },
      { key: "age_months", label: "Tuổi (tháng)", type: "number", list: true },
      { key: "L", label: "L", type: "number", list: true },
      { key: "M", label: "M", type: "number", list: true },
      { key: "S", label: "S", type: "number", list: true },
      { key: "source", label: "Nguồn", type: "text", list: true },
    ],
  },

  /* ------------------------------ CLB ------------------------------ */
  {
    key: "clubs",
    group: "clubs",
    label: "Câu lạc bộ",
    search: ["name", "teacher_name"],
    sort: "name",
    columns: [
      { key: "name", label: "Tên CLB", type: "text", required: true, list: true },
      { key: "sport", label: "Môn", type: "enum", options: SPORT_ORDER.map((k) => ({ value: k, label: SPORTS[k].label })), required: true, list: true },
      { key: "levels", label: "Khối", type: "multi", options: LEVELS.map((l) => ({ value: l.key, label: l.label })), list: true },
      { key: "teacher_id", label: "Tài khoản GV phụ trách", type: "ref", ref: "profiles", list: true },
      { key: "teacher_name", label: "Tên GV (hiển thị)", type: "text", list: true },
      { key: "expected_size", label: "Sĩ số dự kiến", type: "int", list: true },
      { key: "starts_on", label: "Áp dụng từ", type: "date" },
      { key: "ends_on", label: "Đến ngày", type: "date" },
      { key: "note", label: "Ghi chú", type: "textarea" },
      { key: "source", label: "Nguồn", type: "enum", options: [{ value: "tkb", label: "Theo TKB" }, { value: "manual", label: "Phát sinh" }], readOnly: true, list: true },
      created,
    ],
    deleteNote: "Xoá CLB sẽ xoá luôn lịch sinh hoạt, học viên và minh chứng của CLB.",
  },
  {
    key: "club_slots",
    group: "clubs",
    label: "Lịch sinh hoạt CLB",
    search: ["place"],
    sort: "dow",
    filters: ["club_id"],
    noCreated: true,
    columns: [
      { key: "club_id", label: "CLB", type: "ref", ref: "clubs", required: true, list: true },
      { key: "dow", label: "Thứ", type: "enum", options: [1, 2, 3, 4, 5, 6, 0].map((d) => ({ value: d, label: DOW_FULL[d] })), required: true, list: true, numeric: true },
      { key: "start_time", label: "Bắt đầu", type: "time", required: true, list: true },
      { key: "end_time", label: "Kết thúc", type: "time", required: true, list: true },
      { key: "place", label: "Địa điểm", type: "text", required: true, list: true },
    ],
  },
  {
    key: "club_members",
    group: "clubs",
    label: "Học viên CLB",
    search: ["full_name", "class_name"],
    sort: "full_name",
    filters: ["club_id"],
    columns: [
      { key: "club_id", label: "CLB", type: "ref", ref: "clubs", required: true, list: true },
      { key: "full_name", label: "Họ tên", type: "text", required: true, list: true },
      { key: "student_id", label: "Học sinh trong hệ thống", type: "ref", ref: "students", list: true, hint: "Để trống nếu em chưa có trong dữ liệu thể lực" },
      { key: "class_name", label: "Lớp", type: "text", list: true },
      { key: "grade", label: "Khối", type: "text" },
      { key: "note", label: "Ghi chú", type: "textarea" },
      created,
    ],
  },
  {
    key: "evidence_sessions",
    group: "clubs",
    label: "Buổi minh chứng",
    sort: "-session_date",
    filters: ["club_id"],
    canInsert: false,
    note: "Buổi được tạo tự động khi giáo viên chụp ảnh. Ở đây chỉ sửa trạng thái duyệt hoặc xoá.",
    columns: [
      { key: "club_id", label: "CLB", type: "ref", ref: "clubs", list: true, readOnly: true },
      { key: "session_date", label: "Ngày", type: "date", list: true, readOnly: true },
      { key: "status", label: "Trạng thái", type: "enum", options: EVIDENCE_STATUS, required: true, list: true },
      { key: "reason", label: "Lý do từ chối", type: "textarea", list: true },
      { key: "reviewed_by", label: "Người duyệt", type: "ref", ref: "profiles", list: true, readOnly: true },
      { key: "reviewed_at", label: "Lúc duyệt", type: "datetime", readOnly: true },
      created,
    ],
    deleteNote: "Xoá buổi sẽ xoá luôn các ảnh minh chứng của buổi đó.",
  },
  {
    key: "evidence_photos",
    group: "clubs",
    label: "Ảnh minh chứng",
    search: ["code"],
    sort: "-taken_at",
    filters: ["club_id"],
    canInsert: false,
    canUpdate: false,
    canDelete: false,
    note: "Chỉ xem. Ảnh được ghi khi giáo viên chụp trong app; xem ảnh tại Kho ảnh.",
    columns: [
      { key: "code", label: "Mã ảnh", type: "text", list: true },
      { key: "club_id", label: "CLB", type: "ref", ref: "clubs", list: true },
      { key: "taken_by", label: "Người chụp", type: "ref", ref: "profiles", list: true },
      { key: "taken_at", label: "Giờ máy chủ nhận", type: "datetime", list: true },
      { key: "device_time", label: "Giờ trên ảnh", type: "datetime" },
      { key: "distance_m", label: "Cách trường (m)", type: "number", list: true },
      { key: "inside_campus", label: "Trong khuôn viên", type: "bool", list: true },
      { key: "accuracy_m", label: "Sai số GPS (m)", type: "number" },
      { key: "storage_path", label: "Đường dẫn kho", type: "text" },
    ],
  },

  /* ------------------------------ Tài khoản ------------------------------ */
  {
    key: "profiles",
    group: "accounts",
    label: "Tài khoản & vai trò",
    search: ["email", "full_name"],
    sort: "email",
    canInsert: false,
    canDelete: false,
    note: "Tài khoản được tạo khi đăng ký hoặc trong Supabase → Authentication. Ở đây sửa họ tên và vai trò. Muốn gán vai trò trước khi người đó có tài khoản, dùng bảng \"Mời cán bộ\".",
    columns: [
      { key: "email", label: "Email", type: "text", list: true, readOnly: true },
      { key: "full_name", label: "Họ tên", type: "text", list: true },
      { key: "role", label: "Vai trò", type: "enum", options: ROLES, required: true, list: true },
      created,
    ],
  },
  {
    key: "staff_invites",
    group: "accounts",
    label: "Mời cán bộ (gán vai trò theo email)",
    pk: "email",
    search: ["email", "full_name"],
    sort: "email",
    note: "Gán sẵn vai trò theo email: người đó đăng ký hoặc đăng nhập Google là có vai trò ngay. Thêm cho người đã có tài khoản thì vai trò áp dụng luôn (trừ tài khoản admin).",
    columns: [
      { key: "email", label: "Email", type: "text", required: true, list: true, lowercase: true, pkEditable: true },
      { key: "role", label: "Vai trò", type: "enum", options: ROLES.filter((r) => r.value !== "user"), required: true, list: true },
      { key: "full_name", label: "Họ tên", type: "text", list: true },
      created,
    ],
  },

  /* ------------------------------ Hệ thống ------------------------------ */
  {
    key: "app_settings",
    group: "system",
    label: "Cấu hình app",
    pk: "key",
    sort: "key",
    noCreated: true,
    note: "school_location: toạ độ trường (lat, lon) và bán kính khuôn viên (radius, mét) dùng để kiểm tra ảnh minh chứng.",
    columns: [
      { key: "key", label: "Khoá", type: "text", required: true, list: true, pkEditable: true },
      { key: "value", label: "Giá trị (JSON)", type: "json", required: true, list: true },
      { key: "updated_date", label: "Cập nhật", type: "datetime", readOnly: true, list: true },
    ],
  },
  {
    key: "usage_events",
    group: "system",
    label: "Nhật ký sử dụng",
    sort: "-luc",
    search: ["tinh_nang"],
    filters: ["user_id"],
    canInsert: false,
    canUpdate: false,
    canDelete: false,
    noCreated: true,
    note: "Ghi nhận tự động, gửi cho Major OS — chỉ xem.",
    columns: [
      { key: "luc", label: "Lúc", type: "datetime", list: true },
      { key: "tinh_nang", label: "Tính năng", type: "text", list: true },
      { key: "user_id", label: "Cán bộ", type: "ref", ref: "profiles", list: true },
      { key: "student_id", label: "Học sinh (phụ huynh xem)", type: "ref", ref: "students", list: true },
      { key: "so_lan", label: "Số lần", type: "int", list: true },
      { key: "so_phut", label: "Số phút", type: "number", list: true },
      { key: "chi_tiet", label: "Chi tiết", type: "json" },
    ],
  },
  {
    key: "usage_features",
    group: "system",
    label: "Danh mục tính năng",
    pk: "key",
    search: ["key", "ten"],
    sort: "key",
    canInsert: false,
    canUpdate: false,
    canDelete: false,
    noCreated: true,
    columns: [
      { key: "key", label: "Khoá", type: "text", list: true },
      { key: "ten", label: "Tên", type: "text", list: true },
      { key: "nhom", label: "Nhóm", type: "text", list: true },
    ],
  },
];

export const tableByKey = Object.fromEntries(TABLES.map((t) => [t.key, t]));
export const pkOf = (t) => t.pk || "id";
export const can = (t, action) => t[`can${action}`] !== false;
